export * from './education'
export * from './experience'
export * from './misc'
export { default as PhotoPage } from './Photo'
export { default as TestPage } from './Test'
export { default as HomePage } from './Home'
export { default as OSSPage } from './OSS'
